# -*- coding: utf-8 -*-
"""LAGRANGE

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10yZCFkg61Dw5WjxZASu1DOOLg8rQrMRC
"""

from sympy import *

x = symbols('x')


def lagrange(x0, x1, x2, x3, f0, f1, f2, f3, n, interpo):
    l1, l2, l3, resp = 0, 0, 0,0
    polinomio = []
    polinomio.append([x0, x1, x2, x3])
    polinomio.append([f0, f1, f2, f3])
    if n == 1:
        l1 = ((f0)*((x - x1) / (x0 - x1)) + ((f1)*((x - x0) / (x1 - x0))))
        polinomio.append([l1])
    elif n == 2:
        l1 = ((f0)*((x - x1)*(x - x2)) / ((x0 - x1)*(x0 - x2)) + (f1)*((x - x0)*(x - x2)) / ((x1 - x0)(x1 - x2)) + (f2)*((x - x0)*(x - x1)) / ((x2 - x0)*(x2 - x1)))
        polinomio.append([l1])
    elif n == 3:
        l1 = ((f0)*((x - x1)*(x - x2)*(x - x3))/((x0 - x1)*(x0 - x2)*(x0 - x3)) + (f1)*((x - x0)*(x - x2)*(x - x3)) / ((x1 - x0)*(x1 - x2)*(x1 - x3)) + (f2)*((x - x0)*(x - x1)*(x - x3)) / ((x2 - x0)*(x2 - x1)*(x2 - x3)) + (f3)*((x - x0)*(x - x1)*(x - x2)) / ((x3 - x0)*(x3 - x0)*(x3 - x1)*(x3 - x2)))
        polinomio.append([l1])
    interpo = l1.subs(x, interpo)
    if interpo != 0:
        polinomio.append([resp, interpo])
    else:
        polinomio.append([resp])
    return polinomio

lista = []
print (lagrange(56.6,113,181,214.5,1,5,20,40,1,2))
print(lista)